spring:
  # 应用名称
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 应用服务 WEB 访问端口
server:
  port: 30000

cosProperties:
  bucketName: xx
  accessKey: xxxx
  secretKey: xxx
  region: ap-beijing
